import '../../features/academy/models/cohort.dart';
import '../../features/academy/models/student.dart';
import '../../features/roadmap/providers/roadmap_models.dart';
import '../../features/studio/models/build_project.dart';
import '../../features/studio/models/deal.dart';
import '../../features/verified/models/certified_founder.dart';
import '../../features/verified/models/founder_application.dart';
import '../../features/revenue/providers/revenue_models.dart';
import '../theme/app_colors.dart';

class MockData {
  const MockData._();

  static List<Cohort> cohorts() {
    return [
      Cohort(
        id: 'c1',
        name: 'Cohort 1 - Oct 2025',
        studentsEnrolled: 47,
        capacity: 50,
        startDate: DateTime(2025, 10, 7),
        endDate: DateTime(2025, 12, 30),
        status: CohortStatus.completed,
        feeRange: '₹20K-₹35K',
        grossMarginPercent: 78,
        students: const [
          Student(
            id: 's1',
            name: 'Aryan Sharma',
            college: 'LNCT Bhopal',
            city: 'Bhopal',
            tier: CityTier.tier2,
            feeType: FeeType.paid,
            feeAmount: 25000,
            weekProgress: 12,
            studioDeployed: true,
            certified: true,
            placed: true,
          ),
          Student(
            id: 's2',
            name: 'Priya Verma',
            college: 'RGPV Indore',
            city: 'Indore',
            tier: CityTier.tier2,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 12,
            studioDeployed: true,
            certified: true,
            placed: false,
          ),
          Student(
            id: 's3',
            name: 'Nikhil Sahu',
            college: 'Jabalpur Engineering College',
            city: 'Jabalpur',
            tier: CityTier.tier3,
            feeType: FeeType.paid,
            feeAmount: 30000,
            weekProgress: 11,
            studioDeployed: false,
            certified: true,
            placed: true,
          ),
          Student(
            id: 's4',
            name: 'Meera Iyer',
            college: 'PES Mandya',
            city: 'Mandya',
            tier: CityTier.tier3,
            feeType: FeeType.paid,
            feeAmount: 22000,
            weekProgress: 12,
            studioDeployed: true,
            certified: true,
            placed: true,
          ),
          Student(
            id: 's5',
            name: 'Kabir Khan',
            college: 'GEC Rajkot',
            city: 'Rajkot',
            tier: CityTier.tier2,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 10,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
        ],
      ),
      Cohort(
        id: 'c2',
        name: 'Cohort 2 - Jan 2026',
        studentsEnrolled: 38,
        capacity: 50,
        startDate: DateTime(2026, 1, 12),
        endDate: DateTime(2026, 4, 7),
        status: CohortStatus.active,
        feeRange: '₹25K-₹45K',
        grossMarginPercent: 0,
        students: const [
          Student(
            id: 's6',
            name: 'Tanvi Reddy',
            college: 'VIT Bhopal',
            city: 'Bhopal',
            tier: CityTier.tier2,
            feeType: FeeType.paid,
            feeAmount: 35000,
            weekProgress: 8,
            studioDeployed: true,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's7',
            name: 'Devansh Joshi',
            college: 'Medicaps University',
            city: 'Indore',
            tier: CityTier.tier2,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 7,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's8',
            name: 'Aarohi Patil',
            college: 'SIT Tumakuru',
            city: 'Tumakuru',
            tier: CityTier.tier3,
            feeType: FeeType.paid,
            feeAmount: 28000,
            weekProgress: 6,
            studioDeployed: true,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's9',
            name: 'Harshita Jain',
            college: 'RIT Roorkee',
            city: 'Roorkee',
            tier: CityTier.tier3,
            feeType: FeeType.paid,
            feeAmount: 30000,
            weekProgress: 8,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's10',
            name: 'Samar Gill',
            college: 'Chandigarh Group of Colleges',
            city: 'Mohali',
            tier: CityTier.tier2,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 5,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
        ],
      ),
      Cohort(
        id: 'c3',
        name: 'Cohort 3 - Apr 2026',
        studentsEnrolled: 0,
        capacity: 75,
        startDate: DateTime(2026, 4, 20),
        endDate: DateTime(2026, 7, 13),
        status: CohortStatus.upcoming,
        feeRange: '₹30K-₹50K',
        grossMarginPercent: 0,
        students: const [
          Student(
            id: 's11',
            name: 'Ishaan Kulkarni',
            college: 'Walchand Sangli',
            city: 'Sangli',
            tier: CityTier.tier3,
            feeType: FeeType.paid,
            feeAmount: 32000,
            weekProgress: 1,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's12',
            name: 'Sara Mathew',
            college: 'Saintgits Kottayam',
            city: 'Kottayam',
            tier: CityTier.tier3,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 1,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's13',
            name: 'Yash Bansal',
            college: 'JECRC Jaipur',
            city: 'Jaipur',
            tier: CityTier.tier2,
            feeType: FeeType.paid,
            feeAmount: 36000,
            weekProgress: 1,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's14',
            name: 'Ritika Das',
            college: 'KIIT Bhubaneswar',
            city: 'Bhubaneswar',
            tier: CityTier.tier2,
            feeType: FeeType.paid,
            feeAmount: 34000,
            weekProgress: 1,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
          Student(
            id: 's15',
            name: 'Mihir Rao',
            college: 'KLE Technological University',
            city: 'Hubballi',
            tier: CityTier.tier3,
            feeType: FeeType.isa,
            feeAmount: 0,
            weekProgress: 1,
            studioDeployed: false,
            certified: false,
            placed: false,
          ),
        ],
      ),
    ];
  }

  static List<BuildProject> buildProjects() {
    return [
      BuildProject(
        id: 'p1',
        founderName: 'Rahul Mehta',
        startupName: 'FarmConnect',
        description:
            'A procurement network linking farmer producer organizations to urban restaurant buyers.',
        dealType: DealType.equity,
        cashAmount: 150000,
        equityPercent: 12,
        status: BuildStatus.sprint,
        startDate: DateTime(2026, 1, 17),
        techStack: const ['Flutter', 'Firebase', 'Cloud Functions', 'Razorpay'],
        builderCount: 4,
        weeklyProgress: 5,
        retainerMonthly: 0,
      ),
      BuildProject(
        id: 'p2',
        founderName: 'Sarah Chen',
        startupName: 'DocuFlow',
        description:
            'Document intake, approval, and audit workflows for compliance-heavy SMEs.',
        dealType: DealType.cash,
        cashAmount: 750000,
        equityPercent: 0,
        status: BuildStatus.qa,
        startDate: DateTime(2025, 12, 20),
        techStack: const ['Next.js', 'Supabase', 'OpenAI', 'Stripe'],
        builderCount: 3,
        weeklyProgress: 9,
        retainerMonthly: 0,
      ),
      BuildProject(
        id: 'p3',
        founderName: 'Vikram Nair',
        startupName: 'HealthSync',
        description:
            'Clinic follow-up automation with patient reminders and lightweight EMR sync.',
        dealType: DealType.hybrid,
        cashAmount: 300000,
        equityPercent: 5,
        status: BuildStatus.live,
        startDate: DateTime(2025, 11, 18),
        techStack: const ['React', 'Django', 'PostgreSQL', 'WhatsApp API'],
        builderCount: 5,
        weeklyProgress: 10,
        retainerMonthly: 90000,
      ),
      BuildProject(
        id: 'p4',
        founderName: 'Aisha Patel',
        startupName: 'EduTrack',
        description:
            'Outcome tracking for vocational institutes, students, mentors, and hiring partners.',
        dealType: DealType.equity,
        cashAmount: 100000,
        equityPercent: 15,
        status: BuildStatus.discovery,
        startDate: DateTime(2026, 2, 1),
        techStack: const ['Flutter', 'Node.js', 'MongoDB', 'Nexus AI'],
        builderCount: 2,
        weeklyProgress: 2,
        retainerMonthly: 0,
      ),
    ];
  }

  static List<Deal> deals() {
    return [
      Deal(
        id: 'd1',
        type: DealType.equity,
        cashAmount: 150000,
        equityPercent: 12,
        founderName: 'Rahul Mehta',
        signedDate: DateTime(2026, 1, 10),
        status: 'Signed',
      ),
      Deal(
        id: 'd2',
        type: DealType.cash,
        cashAmount: 750000,
        equityPercent: 0,
        founderName: 'Sarah Chen',
        signedDate: DateTime(2025, 12, 15),
        status: 'In delivery',
      ),
      Deal(
        id: 'd3',
        type: DealType.hybrid,
        cashAmount: 300000,
        equityPercent: 5,
        founderName: 'Vikram Nair',
        signedDate: DateTime(2025, 11, 12),
        status: 'Live retainer',
      ),
    ];
  }

  static List<CertifiedFounder> certifiedFounders() {
    return [
      CertifiedFounder(
        id: 'f1',
        founderName: 'Karan Bajaj',
        startupName: 'LogiSmart',
        sector: 'Logistics',
        certDate: DateTime(2026, 1, 18),
        indexScore: 84,
        badgeStatus: BadgeStatus.active,
        annualRenewalDue: DateTime(2027, 1, 18),
        investorIntroCount: 9,
        roundRaisedAmount: 18000000,
      ),
      CertifiedFounder(
        id: 'f2',
        founderName: 'Neha Gupta',
        startupName: 'FinEase',
        sector: 'Fintech',
        certDate: DateTime(2026, 1, 30),
        indexScore: 91,
        badgeStatus: BadgeStatus.active,
        annualRenewalDue: DateTime(2027, 1, 30),
        investorIntroCount: 14,
        roundRaisedAmount: 42000000,
      ),
      CertifiedFounder(
        id: 'f3',
        founderName: 'Rohan Tiwari',
        startupName: 'GreenRoute',
        sector: 'CleanTech',
        certDate: DateTime(2025, 12, 16),
        indexScore: 67,
        badgeStatus: BadgeStatus.active,
        annualRenewalDue: DateTime(2026, 12, 16),
        investorIntroCount: 5,
        roundRaisedAmount: 6500000,
      ),
      CertifiedFounder(
        id: 'f4',
        founderName: 'Maya Krishnan',
        startupName: 'SkillNest',
        sector: 'EdTech',
        certDate: DateTime(2025, 11, 4),
        indexScore: 73,
        badgeStatus: BadgeStatus.expired,
        annualRenewalDue: DateTime(2026, 5, 30),
        investorIntroCount: 3,
        roundRaisedAmount: 0,
      ),
      CertifiedFounder(
        id: 'f5',
        founderName: 'Aditya Rao',
        startupName: 'CredDock',
        sector: 'B2B SaaS',
        certDate: DateTime(2025, 10, 22),
        indexScore: 38,
        badgeStatus: BadgeStatus.revoked,
        annualRenewalDue: DateTime(2026, 10, 22),
        investorIntroCount: 1,
        roundRaisedAmount: 0,
      ),
    ];
  }

  static List<FounderApplication> founderApplications() {
    return [
      FounderApplication(
        id: 'a1',
        founderName: 'Rhea Sen',
        startupName: 'HirePulse',
        submittedDate: DateTime(2026, 2, 2),
        currentLayer: 2,
        layerStatuses: const [
          'passed',
          'pending',
          'pending',
          'pending',
          'pending',
        ],
        totalFeesPaid: 5000,
      ),
      FounderApplication(
        id: 'a2',
        founderName: 'Imran Qureshi',
        startupName: 'MedLedger',
        submittedDate: DateTime(2026, 1, 29),
        currentLayer: 4,
        layerStatuses: const [
          'passed',
          'passed',
          'passed',
          'pending',
          'pending',
        ],
        totalFeesPaid: 5000,
      ),
      FounderApplication(
        id: 'a3',
        founderName: 'Shruti Menon',
        startupName: 'AgriVest',
        submittedDate: DateTime(2026, 2, 5),
        currentLayer: 1,
        layerStatuses: const [
          'pending',
          'pending',
          'pending',
          'pending',
          'pending',
        ],
        totalFeesPaid: 0,
      ),
    ];
  }

  static List<RevenueStream> revenueStreams() {
    return const [
      RevenueStream(
        name: 'Academy cohorts',
        scale: '50-75 students',
        when: 'Live',
        perUnit: '₹25K/student',
        marginPercent: 80,
        color: AppColors.academy,
        active: true,
        critical: true,
      ),
      RevenueStream(
        name: 'Studio builds',
        scale: '4 MVPs/month',
        when: 'Live',
        perUnit: '₹5L/build',
        marginPercent: 64,
        color: AppColors.studio,
        active: true,
        critical: true,
      ),
      RevenueStream(
        name: 'Verified applications',
        scale: '20 founders/month',
        when: 'Q2 2026',
        perUnit: '₹5K/app',
        marginPercent: 87,
        color: AppColors.verified,
        active: true,
      ),
      RevenueStream(
        name: 'Verified renewals',
        scale: '100 renewals/year',
        when: 'Q4 2026',
        perUnit: '₹15K/year',
        marginPercent: 90,
        color: AppColors.verifiedD,
        active: false,
      ),
      RevenueStream(
        name: 'Nexus AI seats',
        scale: '1K builders',
        when: 'Beta',
        perUnit: '₹999/month',
        marginPercent: 76,
        color: AppColors.nexus,
        active: true,
      ),
      RevenueStream(
        name: 'Investor diligence',
        scale: '10 memos/month',
        when: 'Q3 2026',
        perUnit: '₹40K/memo',
        marginPercent: 72,
        color: AppColors.navy2,
        active: false,
      ),
      RevenueStream(
        name: 'Retainers',
        scale: '6 active clients',
        when: 'Live',
        perUnit: '₹90K/month',
        marginPercent: 58,
        color: AppColors.purple2,
        active: true,
      ),
    ];
  }

  static List<Phase> phases(Map<String, bool> completions) {
    bool done(String id, bool fallback) => completions[id] ?? fallback;
    return [
      Phase(
        id: 'phase1',
        monthRange: 'Jan-Mar 2026',
        title: 'Operating Base',
        state: PhaseState.done,
        target: 'Academy + Studio live',
        items: [
          PhaseItem(
            id: 'p1i1',
            description:
                'Run first paid Academy cohorts with full progress tracking',
            completed: done('p1i1', true),
          ),
          PhaseItem(
            id: 'p1i2',
            description: 'Ship two Studio MVPs into production usage',
            completed: done('p1i2', true),
          ),
          PhaseItem(
            id: 'p1i3',
            description:
                'Create founder verification rubric and council cadence',
            completed: done('p1i3', true),
          ),
        ],
      ),
      Phase(
        id: 'phase2',
        monthRange: 'Apr-Jun 2026',
        title: 'Verification Layer',
        state: PhaseState.active,
        target: '50 certified founders',
        items: [
          PhaseItem(
            id: 'p2i1',
            description: 'Launch five-layer Verified application flow',
            completed: done('p2i1', true),
          ),
          PhaseItem(
            id: 'p2i2',
            description:
                'Publish first AlgoForce Index scorecards to investors',
            completed: done('p2i2', false),
          ),
          PhaseItem(
            id: 'p2i3',
            description:
                'Attach Nexus AI builder output to Studio delivery process',
            completed: done('p2i3', false),
          ),
        ],
      ),
      Phase(
        id: 'phase3',
        monthRange: 'Jul-Sep 2026',
        title: 'Capital Network',
        state: PhaseState.upcoming,
        target: '₹2.6 Cr run rate',
        items: [
          PhaseItem(
            id: 'p3i1',
            description: 'Start investor diligence memo subscriptions',
            completed: done('p3i1', false),
          ),
          PhaseItem(
            id: 'p3i2',
            description: 'Convert three live MVPs into retainer clients',
            completed: done('p3i2', false),
          ),
          PhaseItem(
            id: 'p3i3',
            description: 'Grow Nexus beta to one thousand builder users',
            completed: done('p3i3', false),
          ),
        ],
      ),
      Phase(
        id: 'phase4',
        monthRange: 'Oct-Dec 2026',
        title: 'Scale Flywheel',
        state: PhaseState.upcoming,
        target: '₹5.4 Cr ARR path',
        items: [
          PhaseItem(
            id: 'p4i1',
            description: 'Open 2030 builder fellowship applications',
            completed: done('p4i1', false),
          ),
          PhaseItem(
            id: 'p4i2',
            description:
                'Automate annual Verified renewals and revocation workflow',
            completed: done('p4i2', false),
          ),
          PhaseItem(
            id: 'p4i3',
            description:
                'Formalize AlgoForce venture upside portfolio reporting',
            completed: done('p4i3', false),
          ),
        ],
      ),
    ];
  }
}
